# Generated by Django 2.2.3 on 2019-11-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('editora', models.CharField(max_length=255)),
                ('numero_paginas', models.IntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
